@Elaaj.API_HostAddress = https://localhost:7061


GET {{Elaaj.API_HostAddress}}/api/Patients

###

POST {{Elaaj.API_HostAddress}}/api/Patients
Content-Type: application/json

{
  "fullName":"alaa hassan",
  "region": "Cairo"
}

###

@id=6
DELETE {{Elaaj.API_HostAddress}}/api/Patients/{{id}}

###

GET {{Elaaj.API_HostAddress}}/api/Patients/{{id}}

###

PATCH {{Elaaj.API_HostAddress}}/api/Patients/{id}
Content-Type: application/json

{
  "fullName": "Mustafa Yasser",
  "region": "Assiut"
}

###


GET {{Elaaj.API_HostAddress}}/api/pharmacies

###

@id=4
GET {{Elaaj.API_HostAddress}}/api/pharmacies/{{id}}

###
PUT {{Elaaj.API_HostAddress}}/api/pharmacies/{{id}}
Content-Type: application/json

{
  "Id" : 1,
  "name": "Assiut Pharmacy"
}

###

POST {{Elaaj.API_HostAddress}}/api/pharmacies
Content-Type: application/json

{
  "name": "Test4",
  "imageUrl": "",
  "address": "",
  "latitude": 27.120,
  "longitude": 31.18,
  "workingHours": "08:00 AM - 12:00 AM",
  "hasDelivery": true,
  "contactNumber": ""
}

###

DELETE {{Elaaj.API_HostAddress}}/api/pharmacies/{{id}}

###
